apiVersion: v1
kind: Service
metadata:
  name: mysql-writer-service
  namespace: asiayo
spec:
  type: ClusterIP
  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: mysql-0
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-reader-service
  namespace: asiayo
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306