apiVersion: v1
kind: PersistentVolume
metadata:
  name: asiayo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: xxxxxx
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc